name: docker hub login
on: workflow_dispatch
jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: login to dockerhub
        run: echo"${{ secrets.}}" | docker login -u${{ vars.}} --password-stdin
      - name: pull existing image
        run: docker pull nginx:latest
      - name: rename the image
        run: docker image tag nginx:latest ${{ vars.}}/nginx
      - name: list images
        run: docker image ls
      - name: push image to docker hub
        run: docker push ${{ vars.}}/nginx:latest
        
        
